#include<stdio.h>
#include<stdlib.h>
#include<time.h>
int main()
{
	srand(time(NULL));
	int i,a,sum=0;
	for (i=0;i<1;i++)
	a=rand()%52;
	switch(a)
	{
		case'1':
		puts("黑桃A");
		sum=sum+11;
		printf("你的点数:%d",sum);
		case'2':
		puts("方块A");
		sum=sum+11;
		printf("你的点数:%d",sum);
		case'3':
		puts("梅花A");
		sum=sum+11;
		printf("你的点数:%d",sum);
		case'4':
		puts("红心A");
		sum=sum+11;
		printf("你的点数:%d",sum);
		case'5':
		puts("黑桃2");
		sum=sum+2;
		printf("你的点数:%d",sum);
		case'6':
		puts("方块2");
		sum=sum+2;
		printf("你的点数:%d",sum);
		case'7':
		puts("梅花2");
		sum=sum+2;
		printf("你的点数:%d",sum);
		case'8':
		puts("红心2");
		sum=sum+2;
		printf("你的点数:%d",sum);
		case'9':
		puts("黑桃3");
		sum=sum+3;
		printf("你的点数:%d",sum);
	    case'10':
		puts("梅花3");
		sum=sum+3;
		printf("你的点数:%d",sum);
		case'11':
		puts("红心3");
		sum=sum+3;
		printf("你的点数:%d",sum);
		case'12':
		puts("方块3");
		sum=sum+3;
		printf("你的点数:%d",sum);
		case'13':
		puts("黑桃4");
		sum=sum+4;
		printf("你的点数:%d",sum);
		case'14':
		puts("方块4");
		sum=sum+4;
		printf("你的点数:%d",sum);
		case'15':
		puts("梅花4");
		sum=sum+4;
		printf("你的点数:%d",sum);
		case'16':
		puts("红心4");
		sum=sum+4;
		printf("你的点数:%d",sum);
		case'17':
		puts("梅花5");
		sum=sum+5;
		printf("你的点数:%d",sum);
		case'18':
		puts("方块5");
		sum=sum+5;
		printf("你的点数:%d",sum);
		case'19':
		puts("红心5");
		sum=sum+5;
		printf("你的点数:%d",sum);
		case'20':
		puts("黑桃5");
		sum=sum+5;
		printf("你的点数:%d",sum);
		case'21':
		puts("黑桃6");
		sum=sum+6;
		printf("你的点数:%d",sum); 
		case'22':
		puts("方块6");
		sum=sum+6;
	    printf("你的点数:%d",sum);
		case'23':
		puts("红心6");
		sum=sum+6;
		printf("你的点数:%d",sum);
		case'24':
		puts("梅花6");
		sum=sum+6;
		printf("你的点数:%d",sum);
		case'25':
		puts("黑桃7");
		sum=sum+7;
		printf("你的点数:%d",sum);
		case'26':
		puts("方块7");
		sum=sum+7;
		printf("你的点数:%d",sum);
		case'27':
		puts("红心7");
		sum=sum+7;
		printf("你的点数:%d",sum);
		case'28':
		puts("梅花7");
		sum=sum+7;
		printf("你的点数:%d",sum);
		case'29':
		puts("黑桃8");
		sum=sum+8;
		printf("你的点数:%d",sum);
		case'30':
		puts("方块8");
		sum=sum+8;
		printf("你的点数:%d",sum);
		case'31':
		puts("红心8");
		sum=sum+8;
		printf("你的点数:%d",sum);
		case'32':
		puts("梅花8");
		sum=sum+8;
		printf("你的点数:%d",sum);
		case'33':
		puts("黑桃9");
		sum=sum+9;
		printf("你的点数:%d",sum);
		case'34':
		puts("方块9");
		sum=sum+9;
		printf("你的点数:%d",sum);
		case'35':
		puts("红心9");
		sum=sum+9;
		printf("你的点数:%d",sum);
		case'36':
		puts("梅花9");
		sum=sum+9;
	    printf("你的点数:%d",sum);
		case'37':
		puts("黑桃10");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'38':
		puts("方块7");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'39':
		puts("红心10");
		sum=sum+6;
	printf("你的点数:%d",sum);
		case'40': 
		puts("梅花10");
		sum=sum+10; 
		printf("你的点数:%d",sum);
		case'41':
		puts("黑桃J");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'42':
		puts("方块J");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'43':
		puts("红心J");
		sum=sum+10;
	printf("你的点数:%d",sum);
		case'44':
		puts("梅花J");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'45':
		puts("方块K");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'46':
		puts("红心K");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'47':
		puts("梅花K");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'48':
		puts("黑桃K");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'49':
		puts("方块Q");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'50':
		puts("红心Q");
		sum=sum+10;
		printf("你的点数:%d",sum);
		case'51':
		puts("梅花Q");
		sum=sum+10;
	printf("你的点数:%d",sum);
		case'52':
		puts("黑桃Q");
		sum=sum+10;
		printf("你的点数:%d",sum);
		default:
		break;
		
		
		
		
	}
	system("pause");
	return 0;
	
}
